### ISSUE TITLE
Order by Description & Labels Column

### ISSUE THREAD

**Issue by o4f6bgpac3** [forwardemail/forwardemail.net#105]
When using multiple aliases with random addresses (dice feature - very nice by the way!), the order of rows is therefore random as well. It would be desirable to have the option (ideally saved in some way) to order by the Description & Labels column so that it's easier to scroll to the correct position. Find on page works well but column ordering would be better in my opinion.

**Comment by niftylettuce** [comment]
Great suggestion, will try to get this in.

**Comment by niftylettuce** [comment]
This feature is already deployed, does it work well enough for you?

**Comment by mwade290** [comment]
Yes the ordering part works great, thanks!
However, the pagination has made it difficult due to the limited results per page and limited pages you can skip.
So for example, if I have 200 aliases which are random aliases with a readable description, I can order by description and know that one starting with "m" would be somewhere in the middle. The pagination only shows the first 3 pages, then one at a time after that out of x number of pages (the total doesn't show), so I need to keep clicking next page to find the results.
Additionally, the search only searches Alias whereas I need to search Description.

Would you like me to raise 2 other issues for these new problems?

**Comment by niftylettuce** [comment]
@mwade290 we're going to fix this and will ping you back.  no need to file another issue, thanks!

**Comment by mwade290** [comment]
The changes work really well, thank you very much!
