### ISSUE TITLE
Mail Server One is down

### ISSUE THREAD

**Issue by canceI** [forwardemail/forwardemail.net#153]
For about roughly 17 or so hours, the mail server has been flagged by Gmail and any emails sent to or from mails do not get forwarded.

```
Message failed: 550-5.7.1 [138.197.213.185 ((routes back to mx1.forwardmail.net))     12] Our system has detected that this message is
550-5.7.1 likely unsolicited mail. To reduce the amount of spam sent to Gmail,
550-5.7.1 this message has been blocked. Please visit
550-5.7.1  https://support.google.com/mail/?p=UnsolicitedMessageError
550 5.7.1  for more information.```

```

Hopefully, this issue gets fixed soon and lost emails could be received.

**Comment by niftylettuce** [comment]
Thank you for filing this.  The mail server is not down and we are not blocked at the moment by Gmail.  It may have been temporary due to a one-off spammer, and emails should still flow through and be retried.  Emails have been flowing and uptime is 99%.  If you can email me at niftylettuce@gmail.com along with your domain name and where you send FROM and TO that is causing this, I can investigate.
